### ISSUE TITLE
Issue with attachLidarSensor in World.m

### ISSUE THREAD

**Issue by aydinjcan** [yxiao1996/SwarmSim#1]
Hi, there seems to be an issue in like 37 of the world.m file. Apparently, attachLidarSensor shouldn't have input argument 'i'. I'm wondering if this is with the most recent version of Mobile Robotics Simulation Toobox.

**Comment by yxiao1996** [comment]
Hi. This is most likely not with the latest version of mobile robot sim toolbox. I will take a look at it soon. Thanks.

**Comment by yxiao1996** [comment]
The proglam should be solved by now. Noticed that mobile robotics simulation toolbox is included into the /lib folder, since some minor changes are needed for compatibility of latest robotics system toolbox.

**Comment by aydinjcan** [comment]
Fantastic, thanks for getting this sorted so quickly!
